version: '3.8'

services:
  portal-boletim:
    build: .
    restart: unless-stopped
    ports:
      - "3010:3010"   # Front-end Next.js na porta 3010 do host
      - "3011:3011"   # API Express na porta 3011 do host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - PORT=3011
    env_file:
      - .env
